[build]
  publish = "public"
  command = "hugo --buildFuture"

[context.production.environment]
  HUGO_VERSION = "0.155.3"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --buildFuture"

[context.branch-deploy]
  command = "hugo --buildFuture"